package com.example.postgres;

public  class Sql {

    public static final String GET_SUMMARY = "SELECT "+
            "VEHICLEGROUP,QUOTEEFFECTIVEDATE,"+
            "CASE WHEN (ROW_NUMBER() OVER (PARTITION BY BODYTYPE ORDER BY 1)) = 1 THEN BODYTYPE END AS BODYTYPE,"+
            /*"DECODE (ROW_NUMBER() OVER (PARTITION BY TRANSMISSION ORDER BY 1),1,TRANSMISSION) TRANSMISSION,"+*/
            "YEARMADE,COST,"+
            /*"DECODE (ROW_NUMBER() OVER (PARTITION BY OVERNIGHTPARKING ORDER BY 1),1,OVERNIGHTPARKING) OVERNIGHTPARKING,"+
            "DECODE (ROW_NUMBER() OVER (PARTITION BY WHODRIVES ORDER BY 1),1,WHODRIVES) WHODRIVES,"+*/
            "NCBTOTAL,UKRESFLAGADM,"+
            /*"DECODE (ROW_NUMBER() OVER (PARTITION BY USAGETYPE ORDER BY 1),1,USAGETYPE) USAGETYPE,"+
            "DECODE (ROW_NUMBER() OVER (PARTITION BY AGGREGATORID ORDER BY 1),1,AGGREGATORID) AGGREGATORID,"+*/
            "REGISTEREDOWNER,CLAIMSLAST3YRS,CONVLAST5YEARS,CWVALIDTAX,CWVALIDMOT "+
            "FROM MRISK ";



}
